services:
  web:
    image: nginx:latest
    ports:
      - '8008:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: myphp
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
