services:
  web:
    image: nginx:latest
    ports:
      - '8008:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: myphp
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - '8009:8080'
    environment:
      - SQLITE_DATABASE=data.db
    volumes:
      - ./var/data.db:/data/data.db



